version: "3.7"

services:
  app:
    container_name: thuctap_app
    build: .
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.3-bionic
    stdin_open: true
    tty: true
    ports:
      - "27017:27017"
